services:
  cache:
    image: redis:7.0.4-alpine
    # restart: no
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local